# Generated by Django 4.0 on 2021-12-21 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates', models.CharField(max_length=8, verbose_name='Numer rejestracyjny')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Marka')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('fuel', models.CharField(max_length=10, verbose_name='Rodzaj paliwa')),
                ('mileage', models.IntegerField(verbose_name='Przebieg')),
                ('vin', models.CharField(max_length=17, verbose_name='Numer VIN')),
                ('price', models.IntegerField(verbose_name='Cena za 1 dzień')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępny')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Imie')),
                ('surname', models.CharField(max_length=20, verbose_name='Nazwisko')),
                ('mobile', models.CharField(max_length=12, verbose_name='Numer telefonu')),
                ('address', models.CharField(max_length=100, verbose_name='Adres zamieszkania')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('days', models.IntegerField(verbose_name='Liczba dni')),
                ('address', models.CharField(max_length=100, verbose_name='Miejsce wypożyczenia')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client')),
            ],
        ),
    ]
