# Generated by Django 4.0 on 2022-01-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Wartosć wypożyczenia'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.car'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client'),
        ),
    ]
