# Generated by Django 4.0 on 2022-01-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rent_value_alter_rent_car_alter_rent_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='value',
        ),
    ]
