# Generated by Django 4.0 on 2022-01-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_rent_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.car'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.client'),
        ),
    ]
